const dataNews01 = [
    {
        id: 1,
        src: "/img/news2/01/01.avif",
        alt: "01",
        swap: false,
    },
    {
        id: 2,
        src: "/img/news2/01/02.avif",
        alt: "02",
        swap: true,
    },
    {
        id: 3,
        src: "/img/news2/01/03.avif",
        alt: "03",
        swap: false,
    },
    {
        id: 4,
        src: "/img/news2/01/04.avif",
        alt: "04",
        swap: true,
    },
    {
        id: 5,
        src: "/img/news2/01/05.avif",
        alt: "05",
        swap: false,
    },
];

const dataNews02 = [
    {
        id: 1,
        src: "/img/news2/02/01.avif",
        alt: "01",
        swap: false,
    },
    {
        id: 2,
        src: "/img/news2/02/02.avif",
        alt: "02",
        swap: true,
    },
    {
        id: 3,
        src: "/img/news2/02/03.avif",
        alt: "03",
        swap: false,
    },
    {
        id: 4,
        src: "/img/news2/02/04.avif",
        alt: "04",
        swap: true,
    },
    {
        id: 5,
        src: "/img/news2/02/05.avif",
        alt: "05",
        swap: false,
    },
];

const dataNews03 = [
    {
        id: 1,
        src: "/img/news2/03/01.avif",
        alt: "01",
        swap: false,
    },
    {
        id: 2,
        src: "/img/news2/03/02.avif",
        alt: "02",
        swap: true,
    },
    {
        id: 3,
        src: "/img/news2/03/03.avif",
        alt: "03",
        swap: false,
    },
    {
        id: 4,
        src: "/img/news2/03/04.avif",
        alt: "04",
        swap: true,
    },
    {
        id: 5,
        src: "/img/news2/03/05.avif",
        alt: "05",
        swap: false,
    },
    {
        id: 6,
        src: "/img/news2/03/06.avif",
        alt: "06",
        swap: true,
    },
    {
        id: 7,
        src: "/img/news2/03/07.avif",
        alt: "07",
        swap: false,
    },
    {
        id: 8,
        src: "/img/news2/03/08.avif",
        alt: "08",
        swap: true,
    },
    {
        id: 9,
        src: "/img/news2/03/09.avif",
        alt: "09",
        swap: false,
    },
    {
        id: 10,
        src: "/img/news2/03/10.avif",
        alt: "10",
        swap: true,
    },
    {
        id: 11,
        src: "/img/news2/03/11.avif",
        alt: "11",
        swap: false,
    },
    {
        id: 12,
        src: "/img/news2/03/12.avif",
        alt: "12",
        swap: true,
    },
];

const dataNews04 = [
    {
        id: 1,
        src: "/img/news2/04/01.avif",
        alt: "01",
        swap: false,
    },
    {
        id: 2,
        src: "/img/news2/04/02.avif",
        alt: "02",
        swap: true,
    },
    {
        id: 3,
        src: "/img/news2/04/03.avif",
        alt: "03",
        swap: false,
    },
    {
        id: 4,
        src: "/img/news2/04/04.avif",
        alt: "04",
        swap: true,
    },
    {
        id: 5,
        src: "/img/news2/04/05.avif",
        alt: "05",
        swap: false,
    },
    {
        id: 6,
        src: "/img/news2/04/06.avif",
        alt: "06",
        swap: true,
    },
    {
        id: 7,
        src: "/img/news2/04/07.avif",
        alt: "07",
        swap: false,
    },
    {
        id: 8,
        src: "/img/news2/04/08.avif",
        alt: "08",
        swap: true,
    },
    {
        id: 9,
        src: "/img/news2/04/09.avif",
        alt: "09",
        swap: false,
    },
    {
        id: 10,
        src: "/img/news2/04/10.avif",
        alt: "10",
        swap: true,
    },
    {
        id: 11,
        src: "/img/news2/04/11.avif",
        alt: "11",
        swap: false,
    },
    {
        id: 12,
        src: "/img/news2/04/12.avif",
        alt: "12",
        swap: true,
    },
    {
        id: 13,
        src: "/img/news2/04/13.avif",
        alt: "13",
        swap: false,
    },
    {
        id: 14,
        src: "/img/news2/04/14.avif",
        alt: "14",
        swap: true,
    },
    {
        id: 15,
        src: "/img/news2/04/15.avif",
        alt: "15",
        swap: false,
    },
    {
        id: 16,
        src: "/img/news2/04/16.avif",
        alt: "16",
        swap: true,
    },
    {
        id: 17,
        src: "/img/news2/04/17.avif",
        alt: "17",
        swap: false,
    },
    {
        id: 18,
        src: "/img/news2/04/18.avif",
        alt: "18",
        swap: true,
    },
    {
        id: 19,
        src: "/img/news2/04/19.avif",
        alt: "19",
        swap: false,
    },
    {
        id: 20,
        src: "/img/news2/04/20.avif",
        alt: "20",
        swap: true,
    },
    {
        id: 21,
        src: "/img/news2/04/21.avif",
        alt: "21",
        swap: false,
    },
    {
        id: 22,
        src: "/img/news2/04/22.avif",
        alt: "22",
        swap: true,
    },
    {
        id: 23,
        src: "/img/news2/04/23.avif",
        alt: "23",
        swap: false,
    },
];

const dataNews05 = [
    {
        id: 1,
        src: "/img/news2/05/collage_6_revised.avif",
        alt: "01",
        swap: false,
    },
    {
        id: 2,
        src: "/img/news2/05/collage_7_revised.avif",
        alt: "02",
        swap: true,
    },
];

const dataNews06 = [
    {
        id: 1,
        src: "/img/news2/06/01.avif",
        alt: "01",
        swap: false,
    },
    {
        id: 2,
        src: "/img/news2/06/02.avif",
        alt: "02",
        swap: true,
    },
    {
        id: 3,
        src: "/img/news2/06/03.avif",
        alt: "03",
        swap: false,
    },
    {
        id: 4,
        src: "/img/news2/06/04.avif",
        alt: "04",
        swap: true,
    },
];

const dataNews07 = [
    {
        id: 1,
        src: "/img/news2/07/01.avif",
        alt: "01",
        swap: false,
    },
];

const dataNews08 = [
    {
        id: 1,
        src: "/img/news2/08/collage_1_revised.avif",
        alt: "01",
        swap: false,
    },
    {
        id: 2,
        src: "/img/news2/08/collage_2_revised.avif",
        alt: "02",
        swap: true,
    },
    {
        id: 3,
        src: "/img/news2/08/collage_3_revised.avif",
        alt: "03",
        swap: false,
    },
];
const dataNews09 = [
    {
        id: 1,
        src: "/img/news2/09/01.avif",
        alt: "01",
        swap: false,
    },
    {
        id: 2,
        src: "/img/news2/09/02.avif",
        alt: "02",
        swap: true,
    },
    {
        id: 3,
        src: "/img/news2/09/03.avif",
        alt: "03",
        swap: false,
    },
    {
        id: 4,
        src: "/img/news2/09/04.avif",
        alt: "04",
        swap: true,
    },
    {
        id: 5,
        src: "/img/news2/09/05.avif",
        alt: "05",
        swap: false,
    },
    {
        id: 6,
        src: "/img/news2/09/06.avif",
        alt: "06",
        swap: true,
    },
    {
        id: 7,
        src: "/img/news2/09/07.avif",
        alt: "07",
        swap: false,
    },
    {
        id: 8,
        src: "/img/news2/09/08.avif",
        alt: "08",
        swap: true,
    },
    {
        id: 9,
        src: "/img/news2/09/09.avif",
        alt: "09",
        swap: false,
    },
    {
        id: 10,
        src: "/img/news2/09/10.avif",
        alt: "10",
        swap: true,
    },
    {
        id: 11,
        src: "/img/news2/09/11.avif",
        alt: "11",
        swap: false,
    },
    {
        id: 12,
        src: "/img/news2/09/12.avif",
        alt: "12",
        swap: true,
    },
];
const dataNews10 = [
    {
        id: 1,
        src: "/img/news2/10/bidc2024_pic.avif",
        alt: "01",
        swap: false,
    },
];
const dataNews11 = [
    {
        id: 1,
        src: "/img/news2/11.avif",
        alt: "dataNews11",
        swap: false,
        other: "other",
    },
];
const dataNews12 = [
    {
        id: 1,
        src: "/img/news2/12/00.avif",
        alt: "data12_00",
        swap: false,
    },
    {
        id: 2,
        src: "/img/news2/12/01.avif",
        alt: "data12_01",
        swap: true,
    },
    {
        id: 3,
        src: "/img/news2/12/02.avif",
        alt: "data12_02",
        swap: false,
    },
    {
        id: 4,
        src: "/img/news2/12/03.avif",
        alt: "data12_03",
        swap: true,
    },
    {
        id: 5,
        src: "/img/news2/12/04.avif",
        alt: "data12_04",
        swap: false,
    },
    {
        id: 6,
        src: "/img/news2/12/05.avif",
        alt: "data12_05",
        swap: true,
    },
    {
        id: 7,
        src: "/img/news2/12/06.avif",
        alt: "data12_06",
        swap: false,
    },
    {
        id: 8,
        src: "/img/news2/12/07.avif",
        alt: "data12_07",
        swap: true,
    },
    {
        id: 9,
        src: "/img/news2/12/08.avif",
        alt: "data12_08",
        swap: false,
    },
    {
        id: 10,
        src: "/img/news2/12/09.avif",
        alt: "data12_09",
        swap: true,
    },
    {
        id: 11,
        src: "/img/news2/12/10.avif",
        alt: "data12_10",
        swap: false,
    },
    {
        id: 12,
        src: "/img/news2/12/11.avif",
        alt: "data12_11",
        swap: true,
    },
    {
        id: 13,
        src: "/img/news2/12/12.avif",
        alt: "data12_12",
        swap: false,
    },
    {
        id: 14,
        src: "/img/news2/12/13.avif",
        alt: "data12_13",
        swap: true,
    },
];

const dataNews14 = [
    {
        id: 1,
        src: "/img/news2/14/1_20260724.avif",
        alt: "data14_1",
        swap: false,
    },
    {
        id: 2,
        src: "/img/news2/14/2_20260724.avif",
        alt: "data14_2",
        swap: true,
    },
    {
        id: 3,
        src: "/img/news2/14/3_20260724.avif",
        alt: "data14_3",
        swap: false,
    },
    {
        id: 4,
        src: "/img/news2/14/4_20260724.avif",
        alt: "data14_4",
        swap: true,
    },
    {
        id: 5,
        src: "/img/news2/14/5_20260724.avif",
        alt: "data14_5",
        swap: false,
    },
    {
        id: 6,
        src: "/img/news2/14/6_20260724.avif",
        alt: "data14_6",
        swap: true,
    },
    {
        id: 7,
        src: "/img/news2/14/7_20260724.avif",
        alt: "data14_7",
        swap: false,
    },
];

const dataNews15 = [
    {
        id: 1,
        src: "/img/news2/15/01.jpeg",
        alt: "data15_1",
        swap: false,
    },
    {
        id: 2,
        src: "/img/news2/15/02.jpeg",
        alt: "data15_2",
        swap: true,
    },
    {
        id: 3,
        src: "/img/news2/15/03.jpeg",
        alt: "data15_3",
        swap: false,
    },
    {
        id: 4,
        src: "/img/news2/15/04.jpeg",
        alt: "data15_4",
        swap: true,
    },
    {
        id: 5,
        src: "/img/news2/15/05.jpeg",
        alt: "data15_5",
        swap: false,
    },
    {
        id: 6,
        src: "/img/news2/15/06.jpeg",
        alt: "data15_6",
        swap: true,
    },
    {
        id: 7,
        src: "/img/news2/15/07.jpeg",
        alt: "data15_7",
        swap: false,
    },
    {
        id: 8,
        src: "/img/news2/15/08.jpeg",
        alt: "data15_8",
        swap: true,
    },
    {
        id: 9,
        src: "/img/news2/15/09.jpeg",
        alt: "data15_9",
        swap: false,
    },
    {
        id: 10,
        src: "/img/news2/15/10.jpeg",
        alt: "data15_10",
        swap: true,
    },   
];

const dataNews16 = [
    {
        id: 1,
        src: "/img/news2/16/v_01_01.jpeg",
        alt: "data16_1",
        swap: false,
    },
    {
        id: 2,
        src: "/img/news2/16/v_01_02.jpeg",
        alt: "data16_2",
        swap: true,
    },
    {
        id: 3,
        src: "/img/news2/16/v_01_03.jpeg",
        alt: "data16_3",
        swap: false,
    },
];

export const dataNews = [
    {
        id: 35,
        date: "July 23, 2026",
        title: "A major milestone for Big Brain Studio!",
        src: "/img/news2/14.avif",
        content: `ก้าวสำคัญครั้งใหม่ของ Big Brain Studio! พวกเราขอขอบคุณทาง GDH และ อิทธิปาทา ที่ให้โอกาส ความไว้วางใจ และมาร่วมเป็นกำลังสำคัญในการผลักดันโปรเจกต์แอนิเมชันเรื่องแรกของพวกเรา! 🙏✨`,
        content2: `เป็นก้าวที่ใหญ่และท้าทายมาก แต่สัญญาเลยว่าทีมงานทุกคนจะปล่อยของเต็มที่ ไม่ทำให้ผิดหวังแน่นอน รอติดตามความสนุกกันได้ เร็วๆนี้นะครับ ✌️😊`,
        content3: `Huge thanks to GDH and Ittipata for believing in us and coming onboard as key partners for our very first animated series. It’s a massive step and a thrilling challenge, but we promise to bring our absolute best to the screen.`,
        content4: `We won't let you down—stay tuned for the chaotic fun coming your way soon! 🙏✨😊✌️`,
        to: dataNews14,
        swap: false,
    },
    {
        id: 34,
        date: "July 22, 2026",
        title: "Thailand Content Market 2026",
        src: "/img/news2/16.jpeg",
        content: `That’s a wrap on Thailand Content Market 2026! 🎉`,   
        content2: `We’re truly grateful for the amazing support, conversations, and connections from everyone, both at our booth and during the Business Matching sessions throughout all 3 days.`,   
        content3: `Thank you to everyone who stopped by to chat, connect with us, exchange ideas, and join in on our activities.`,
        content4: `Thank you from the bottom of our hearts, and we hope to see you all again next year! 🤝✨`,
        content5: `.`,
        content6: `ปิดฉากไปอย่างสวยงามสำหรับ Thailand Content Market 2026! 🎉`,
        content7: `ขอบคุณสำหรับการตอบรับที่ดีมากๆ จากทุกคน ทั้งที่บู๊ทของเรา และ Business Matching ตลอดทั้ง3วัน`,
        content8: `ขอขอบคุณทุกคนที่แวะมาพูดคุย ทำความรู้จัก แลกเปลี่ยนไอเดีย และร่วมสนุกกับกิจกรรมของเรา `,
        content9: `ขอบคุณจากใจจริงและหวังว่าจะได้พบทุกคนอีกครั้งในปีหน้าครับ! 🤝✨`,   
        content10: `.`,   
        content11: `#BigBrainStudio #ThailandContentMarket2026 #TCM2026 #BusinessMatching #Animation`,
        to: dataNews16,
        swap: true,
    },
    {
        id: 33,
        date: "July 01, 2026",
        title: "Big Brain Studio Wraps Up Annecy 2026",
        src: "/img/news2/15.jpeg",
        content: `Big Brain Studio wrapped up another inspiring week at Annecy Festival 2026!`,
        content2: `A highlight this year was an exciting seminar on the development of the animation industry, with a special spotlight on Southeast Asian animation. We were thrilled to see Violinist win a prize at the festival, celebrating the growing talent and creativity from the SEA region.`,
        content3: `Beyond the events, Annecy was all about great connections, meeting new friends, reconnecting with familiar faces, and catching up with old ones. And yes, the heat wave definitely made things memorable! ☀️`,
        content4: `Thank you to everyone who made Annecy 2026 such a great experience. See you next time!`,
        to: dataNews15,
        swap: false,
    },
    {
        id: 32,
        date: "Sep 10, 2025",
        title: `We made it! Our project has been officially selected for TCCF 2025 Pitching! Thank you to the TCCF jury. We’re so excited to bring our story to the stage, see you in Taiwan!`,
        src: "/img/news2/13.avif",
        content: null,
        to: "https://www.tccf.tw/en/pitching/selected_entries2025",
        swap: true,
    },
    {
        id: 31,
        date: "July 29, 2025",
        title: "Big Brain Studio Wraps Up a Creative Journey at Annecy 2025!",
        src: "/img/news2/12_00.avif",
        content: `Big Brain Studio had an inspiring time at the Annecy International Animation Film Festival 2025. We were proud to team up with Eez Studio and Tomogram Studio as part of the SEA Pitch for A Letter to Hanako. It was a privilege to support this heartfelt project and share the stage with such talented regional partners.`,
        content2: `From exciting pitch sessions to meaningful conversations with global creatives, Annecy was a celebration of collaboration and storytelling.`,
        content3: `Thank you to everyone who connected with us, see you next year!`,
        to: dataNews12,
        swap: false,
    },

    // {
    //     id: 30,
    //     date: "Mar 24, 2025",
    //     title: "Big Brain Studio and J-Cube (Korea) Officially Join Forces for 2D Anime Productions!",
    //     src: "/img/news2/11.avif",
    //     content: `Big Brain Studio and J-Cube (Korea) have joined forces to collaborate on 2D anime productions. With our combined strengths, this partnership promises outstanding 2D animation. We’re excited to work together and push the boundaries of 2D anime in Korea, Japan, Thailand, and beyond. `,
    //     content2: `การผจญภัยครั้งใหม่ของพวกเราได้เริ่มต้นขึ้นแล้ว! Big Brain Studio and J-Cube (Korea) ได้ร่วมมือกันอย่างเป็นทางการ เพื่อสร้างสรรค์ผลงาน 2D Anime ร่วมกันอย่างเต็มที่ เรามุ่งมั่นที่จะพาอนิเมะ 2 มิติของเราไปสู่มิติใหม่ๆ ทั้งในเกาหลี ญี่ปุ่น ไทย และอีกหลากหลายประเทศทั่วโลก!`,
    //     to: dataNews11,
    //     swap: false,
    // },
    {
        id: 29,
        date: "Sep 16, 2024",
        title: "New vibes at BIDC 2024",
        src: "/img/news2/10.avif",
        content: `We had a productive time at BIDC 2024, connecting with industry peers from around the globe.`,
        content2: `It was a valuable opportunity to build relationships and explore potential projects.`,
        content3: `We’re excited to see how these new connections will develop and lead to future collaborations!`,
        to: dataNews10,
        swap: true,
    },
    {
        id: 28,
        date: "Sep 16, 2024",
        title: "Returning to Annecy Festival 2024",
        src: "/img/news2/09.avif",
        content: `Big Brain Studio made a vibrant return to the Annecy Animation Festival 2024, where we had the pleasure of connecting with creative minds and studios from around the world.`,
        content2: `The exchange of ideas and insights during this dynamic event was truly inspiring.`,
        content3: `See you next year!`,
        to: dataNews09,
        swap: false,
    },
    {
        id: 27,
        date: "June 17, 2024",
        title: "We're excited to share the recent interview of our CEO, Auchara Kijkanjanas, with Mr. Gavin Blair, now live on 'THE CREDITS'— by the Motion Picture Association. A huge thank you for the fantastic feature!",
        src: "/img/news/00.avif",
        content: null,
        to: "https://www.motionpictures.org/2024/06/pioneering-producer-auchara-kijkanjanas-on-animating-thailands-entertainment-industry",
        swap: true,
    },
    {
        id: 26,
        date: "September 30, 2023",
        title2: "Kre8tif 2023: ",
        title: "Latest Project Pitch and Big Brain Studio Showcase at KLCC, Kuala Lumpur",
        src: "/img/news2/08.avif",
        content: `Ker8tif 2023 brought a wave of excitement! We felt incredibly honored to have the opportunity to be a part of elevator pitch session to present our groundbreaking ideas to esteemed judges from leading broadcasters and respected industry experts.`,
        content2: `The invaluable feedback and insights we received were genuinely enriching.`,
        content3: `Showcasing our creative journey at our booth was equally delightful.`,
        content4: `Meeting and connecting with fellow creative minds and exploring potential collaborations was an incredibly positive experience.`,
        content5: `We are grateful for the memorable time we had in Kuala Lumpur!`,
        to: dataNews08,
        swap: false,
    },
    {
        id: 25,
        date: "August 30, 2023",
        title: "Studio Tour Welcomes Our Friend, Hide and Seed",
        src: "/img/news2/07.avif",
        content: `After our quick meet up at Annecy 2023, it was awesome to have Kin Lek Chaw from Hide and Seeds Production (MY) visit our studio.`,
        content2: `We had a great time chatting about the animation industry and are definitely looking forward to teaming up soon!`,
        to: dataNews07,
        swap: true,
    },
    {
        id: 24,
        date: "June 21, 2023",
        title2: "Glad to Host: ",
        title: "Armada TMT Studio, the French Embassy, Warner Bros Discovery, and Yomzeo Studio Pay Us a Friendly Visit!",
        src: "/img/news2/06.avif",
        content: `Our studio was delighted to welcome our esteemed guests.`,
        content2: `We extend our gratitude to Ms. Onmadee 'Cherry' Purapati from TACGA for arranging the visit, which included Mr. Sidi Benlarbi from Armada TMT/Xilam Studio (VN/FR), as well as Mr. Jérémy Segay and Mr. Julien Lacorne from the French Embassy.`,
        content3: `We also had the pleasure of hosting Mr. Andre Seungwook Lee from Yomzeo (KR/FR), and last but not least, Ms. Carlene Tan from Warner Bros Discovery (SG). We had an amazing time together, and we're eagerly anticipating future collaborative opportunities.`,
        content4: `Stay tuned for exciting ventures!`,
        to: dataNews06,
        swap: false,
    },
    {
        id: 23,
        date: "June 18, 2023",
        title2: "Back Onsite: ",
        title: "Big Brain Studio at Bangkok International Digital Content Festival 2023",
        src: "/img/news2/05.avif",
        content: `Big Brain Studio was honored to have been included in the Thailand Pavilion at the esteemed Annecy Animation Festival 2023.`,
        content2: `It was a delightful experience engaging with talented individuals and studios from across the globe, as we shared and exchanged our creative insights during this exhilarating event.`,
        content3: `We look forward to reuniting next year!`,
        to: dataNews05,
        swap: true,
    },
    {
        id: 22,
        date: "July 01, 2023",
        title: "Work Hard, Play Hard - Explore Thailand with Big Brain Studio",
        src: "/img/news2/04.avif",
        content: `After some hard work, we're taking a break to enjoy Thailand's beauty, recharge our creative energy, and uncover hidden gems right in our backyard.`,
        content2: `It's been a blast! We've engaged in lots of fun activities, creating unforgettable memories along the way.`,
        to: dataNews04,
        swap: false,
    },
    {
        id: 21,
        date: "June 17, 2023",
        title: "Big Brain Studio at Annecy Animation Festival 2023",
        src: "/img/news2/03.avif",
        content: `Big Brain Studio was honored to have been included in the Thailand Pavilion at the esteemed Annecy Animation Festival 2023.`,
        content2: `It was a delightful experience engaging with talented individuals and studios from across the globe, as we shared and exchanged our creative insights during this exhilarating event.`,
        content3: `We look forward to reuniting next year!`,
        to: dataNews03,
        swap: true,
    },
    {
        id: 20,
        date: "April 27, 2023",
        title: "Welcome Conan O'Brien to Big Brain Studio!",
        src: "/img/news2/02.avif",
        content: `We recently had the honor of hosting a visit from the legendary Conan O'Brien at our studio, and it was truly a delightful experience.`,
        content2: `Laughter filled the air as we spent a pleasant time together, sharing some good laughs.`,
        to: dataNews02,
        swap: false,
    },
    {
        id: 19,
        date: "March 16, 2023",
        title: "Big Brain Studio at Hong Kong FILMART 2023",
        src: "/img/news2/01.avif",
        content: `After a pandemic pause, Big Brain Studio was thrilled to be at Hong Kong International Film & TV Market (FILMART) this year.`,
        content2: `It was a pleasure to meet Mr. JAYAKUMAR P., CEO of Toonz Media Group(IN), to catch up with our co-production project.`,
        content3: `Our "Hey! Buddy" is on the horizon, something extraordinary is coming your way!`,
        to: dataNews01,
        swap: true,
    },
    {
        id: 18,
        date: "August 30, 2020",
        title: "Covid Pandemic ของ Big Brain Pictures คว้ารางวัล Best Animated Short สาขา Animation & Visual Effect",
        src: "/img/news/01.avif",
        content: null,
        to: "https://www.facebook.com/plugins/video.php?href=https%3A%2F%2Fwww.facebook.com%2Fbidc.fest%2Fvideos%2F626999371281434%2F",
        // to: "https://www.facebook.com/bidc.fest/videos/626999371281434/?redirect=false",
        swap: false,
    },
    {
        id: 17,
        date: "August 27, 2020",
        title: "BidcAward สาขา Animation & Visual Effect Best VFX in TV Commercial",
        src: "/img/news/02.avif",
        content: null,
        to: "https://www.facebook.com/plugins/post.php?href=https%3A%2F%2Fwww.facebook.com%2Fbidc.fest%2Fposts%2Fpfbid0XmJaYYomXbchhMzwoGaNjGuqitS2FJcjGafPH8Et5AyZLn3idGanRvtRMBhyWqbAl",

        // to: "https://www.facebook.com/823379977752236/posts/3281749348581941/?d=n",
        swap: true,
    },
    {
        id: 16,
        date: "September 20, 2019",
        title: "วันนัดรวมตัวของผู้ประกอบการ และผู้สนใจนำงานด้านดิจิทัลคอนเทนต์ไปต่อยอดธุรกิจ ภาคเช้ามีกิจกรรมสนทนาถึงความสำเร็จของกิจกรรมพัฒนาเครือข่าย Digital Content",
        src: "/img/news/03.avif",
        content: null,
        to: "https://www.thansettakij.com/content/409428",
        swap: false,
    },
    {
        id: 15,
        date: "February 22, 2018",
        title: "VMware ผู้ให้บริการเทคโนโยลีชั้นนำและบริการระบบเสมือนจริงแบบ Cloud  จัดงานประกาศรางวัลพันธมิตรยอดเยี่ยม ที่สยามสมาคมในพระบรมราชูปถัมป์",
        src: "/img/news/04.avif",
        content: null,
        to: false,
        swap: true,
    },
    {
        id: 14,
        date: "January 25, 2018",
        title: "AIS Business Solutions ได้จัดงานสัมมนาในหัวข้อ “AIS Cloud Solutions for Animation Industry” ซึ่งเน้นให้ความรู้เกี่ยวกับเทคโนโลยี พร้อมเจาะลึกเรื่องการนำเทคโนโลยี Cloud มาใช้ประโยชน์ในธุรกิจผู้ผลิต Animation ในเมืองไทย",
        src: "/img/news/05.avif",
        content: null,

        to: "https://www.facebook.com/plugins/post.php?href=https%3A%2F%2Fwww.facebook.com%2FAISBusinessSolution%2Fposts%2Fpfbid0wp2ULpXXjYictoWsQrcPHNsjTn3aKcK2eS6dHN4NovH2JwvM4rvpAHYiJ2yM6kATl",
        swap: false,
    },
    {
        id: 13,
        date: "December 04, 2017",
        title: "อุ๋ย นนทรีย์ - ตั้ม อัจฉรา ถ่ายทอดความประทับใจในภาพยนตร์แอนิเมชัน ของขวัญจากดิน",
        src: "/img/news/06.avif",
        content: null,
        to: "https://www.bugaboo.tv/watch/354038",
        swap: true,
    },
    {
        id: 12,
        date: "December 4, 2017",
        title: `ทีมผู้สร้างชวนดู "ของขวัญจากดิน" ภาพยนตร์อนิเมชั่นเพื่อคนไทย`,
        src: "/img/news/07.avif",
        content: null,
        to: "https://www.youtube.com/embed/At60iuM6EvE",
        swap: false,
    },
    {
        id: 11,
        date: "November 27, 2017",
        title: "ของขวัญจากดิน แอนิเมชั่นเทิดพระเกียรติตามรอยแนวคิดศาสตร์พระราชา",
        src: "/img/news/08.avif",
        content: null,
        // to: "https://mono29.com/episode/181888.html",
        to: "https://seeme.me/ch/entertainmentnow/embed/kp2QmM",
        swap: true,
    },
    {
        id: 10,
        date: "November 24, 2017",
        title: `แอนิเมชั่นเล่าศาสตร์พระราชา "ของขวัญจากดิน"ฉายทางทีวีทั่วประเทศ`,
        src: "/img/news/09.avif",
        content: null,
        to: "https://www.youtube.com/embed/bU5_w4PuH1A",
        swap: false,
    },
    {
        id: 9,
        date: "November 23, 2017",
        title: "แถลงข่าวเปิดตัวภาพยนตร์แอนิเมชั่นเทิดพระเกียรติ “ของขวัญจากดิน”",
        src: "/img/news/10.avif",
        content: null,
        to: "https://www.youtube.com/embed/vRrbwB9I0Zo",
        swap: true,
    },
    {
        id: 8,
        date: "November 23, 2017",
        title: `ม.มหิดล โดย โครงการจัดตั้งศูนย์เศรษฐกิจสร้างสรรค์ จัดแถลงข่าวภาพยนตร์แอนิเมชั่น “ของขวัญจากดิน”`,
        src: "/img/news/11.avif",
        content: null,
        to: "https://mahidol.ac.th/th/2017/khongkwan-2/",
        swap: false,
    },
    {
        id: 7,
        date: "November 23, 2017",
        title: `แถลงข่าวเปิดตัวภาพยนตร์แอนิเมชั่นเทิดพระเกียรติ “ของขวัญจากดิน"`,
        src: "/img/news/12.avif",
        content: null,
        to: "https://www.youtube.com/embed/vRrbwB9I0Zo",
        swap: true,
    },
    {
        id: 6,
        date: "April 7, 2017",
        title: `ธนาคารกรุงเทพ รับ 2 รางวัลดีเด่น จากสติ๊กเกอร์ไลน์ Blink Blink ในงาน “Bangkok International Digital Content Festival 2017” เตรียมเปิดตัวชุดใหม่รับสงกรานต์`,
        src: "/img/news/13.avif",
        content: null,
        to: "http://www.moneyandbanking.co.th/new/13824/7/%E0%B8%98%E0%B8%99%E0%B8%B2%E0%B8%84%E0%B8%B2%E0%B8%A3%E0%B8%81%E0%B8%A3%E0%B8%B8%E0%B8%87%E0%B9%80%E0%B8%97%E0%B8%9E-%E0%B8%A3%E0%B8%B1%E0%B8%9A-2-%E0%B8%A3%E0%B8%B2%E0%B8%87%E0%B8%A7%E0%B8%B1%E0%B8%A5%E0%B8%94%E0%B8%B5%E0%B9%80%E0%B8%94%E0%B9%88%E0%B8%99-%E0%B8%88%E0%B8%B2%E0%B8%81%E0%B8%AA%E0%B8%95%E0%B8%B4%E0%B9%8A%E0%B8%81%E0%B9%80%E0%B8%81%E0%B8%AD%E0%B8%A3%E0%B9%8C%E0%B9%84%E0%B8%A5%E0%B8%99%E0%B9%8C",
        swap: false,
    },
    {
        id: 5,
        date: "2016",
        title: `เยี่ยมโครงการส่วนพระองค์ สวนจิตรลดา แหล่งทดลองและจุดกำเนิดของโครงการพระราชดำริในพระบาทสมเด็จพระปรมินทรมหาภูมิพลอดุลยเดชบรมนาถบพิตร`,
        src: "/img/news/14.avif",
        content: null,
        to: false,
        swap: true,
    },
    {
        id: 4,
        date: "2016",
        title: `ศึกษาดูงาน “ประเพณีบุญบั้งไฟ” บูชาพญาแถนขอฝน จังหวัดชัยภูมิ`,
        src: "/img/news/15.avif",
        content: null,
        to: false,
        swap: false,
    },
    {
        id: 3,
        date: "2016",
        title: `เยี่ยมโครงการโรงเรียนกาสรกสิวิทย์ จังหวัดสระแก้ว โรงเรียนที่ฝึกกระบือให้เชื่องและไถนาได้อย่างชำนาญ`,
        src: "/img/news/16.avif",
        content: null,
        to: false,
        swap: true,
    },
    {
        id: 2,
        date: "2016",
        title: `ศึกษาดูงานสถาปัตยกรรมของภาคอีสาน “หมู่บ้านอีสาน จิม ทอมป์สัน ฟาร์ม” จังหวัดนครราชสีมา`,
        src: "/img/news/17.avif",
        content: null,
        to: false,
        swap: false,
    },
    {
        id: 1,
        date: "2013",
        title: `Promote Yourself: 24 Brand-New Asian Projects to be Unveiled at 2013 Asian Animation Summit`,
        src: "/img/news/18.avif",
        content: null,
        to: "http://www.animationinsider.com/2013/11/page/3/",
        swap: true,
    },
];
