
export const workData = [
        {
            id: 1,
            title: "2015-00_blinkblink",
            header: "Blink Blink - 2015",
            img: "/img/ourwork/_QC/2015-00_blinkblink/poster_blinkblink_group_stand.avif",
            link: "/ourwork/blinkblink",
            year: "2015",
            slide1: "/img/ourwork/_QC/2015-00_blinkblink/Slide30.avif",
            video: "/img/ourwork/_QC/2015-00_blinkblink/Blink_Blink_Family_สุขสันต์วันสงกรานต์.mp4",
        },
        {
            id: 2,
            title: "2019-01_gift_of_theland",
            header: "Gift of The Land - 2019",
            img: "/img/ourwork/_QC/2019-01_gift_of_theland/gifts_of_the_land_poster.avif",
            link: "/ourwork/giftoftheland",
            year: "2019",
            slide1: "/img/ourwork/_QC/2019-01_gift_of_theland/สไลด์1.avif",
            video: "/img/ourwork/_QC/2019-01_gift_of_theland/bbs_gift_of_theland.mp4",
        },
        {
            id: 3,
            title: "2022-02_rpf",
            header: "a miracle journey behind the mist - 2022",
            img: "/img/ourwork/_QC/2022-02_rpf/rpf_poster.avif",
            link: "/ourwork/rpf",
            year: "2022",
            slide1: "/img/ourwork/_QC/2022-02_rpf/สไลด์1.avif",
            slide2: "/img/ourwork/_QC/2022-02_rpf/สไลด์2.avif",
            video: "/img/ourwork/_QC/2022-02_rpf/bbs_royal_project_foundation.mp4",
        },
        {
            id: 4,
            title: "2023-01_wisdom1",
            header: "Wisdom King - The Magical Box - 2023",
            img: "/img/ourwork/_QC/2023-01_wisdom1/wisdom_poster.avif",
            link: "/ourwork/wisdom1",
            year: "2023",
            slide1: "/img/ourwork/_QC/2023-01_wisdom1/สไลด์1.avif",
            slide2: "/img/ourwork/_QC/2023-01_wisdom1/สไลด์2.avif",
            video: "/img/ourwork/_QC/2023-01_wisdom1/bbs_wisdom_The_Magical_Box.mp4",
        },
        {
            id: 5,
            title: "2023-02_Mythophobia_online_game",
            header: "Mythophobia online game - 2023",
            img: "/img/ourwork/_QC/2023-02_Mythophobia_online_game/poster.avif",
            link: "/ourwork/mythophobiaonlinegame",
            year: "2023",
            slide1: "/img/ourwork/_QC/2023-02_Mythophobia_online_game/Slide9.avif",
            video: "/img/ourwork/_QC/2023-02_Mythophobia_online_game/ghost.mp4",
        },
        {
            id: 6,
            title: "2023-03Naka_De_Salon",
            header: "Naka De Salon - 2023",
            img: "/img/ourwork/_QC/2023-03_Naka_De_Salon/naka_de_salon_poster.avif",
            link: "/ourwork/nakadesalon",
            year: "2023",
            slide1: "/img/ourwork/_QC/2023-03_Naka_De_Salon/Naka_De_Salon.avif",
            video: "/img/ourwork/_QC/2023-03_Naka_De_Salon/Naka_De_Salon.mp4",
        },
        {
            id: 7,
            title: "2024-01_wisdom2",
            header: "Wisdom King - Guardians of The Dawn - 2024",
            img: "/img/ourwork/_QC/2024-01_wisdom2/wdk2_poster_02.avif",
            link: "/ourwork/wisdom2",
            year: "2024",
            slide1: "/img/ourwork/_QC/2024-01_wisdom2/สไลด์1.avif",
            slide2: "/img/ourwork/_QC/2024-01_wisdom2/สไลด์2.avif",
            video: "/img/ourwork/_QC/2024-01_wisdom2/bbs_wisdom_Guardians_of_The_Dawn.mp4",
        },
        {
            id: 8,
            title: "2024-02_EGAT_Smart_Grid",
            header: "EGAT Smart Grid Maehongson - 2024",
            img: "/img/ourwork/_QC/2024-02_EGAT_Smart_Grid/egat_smartgrid_poster_01.avif",
            link: "/ourwork/egatsmartgrid",
            year: "2024",
            slide1: "/img/ourwork/_QC/2024-02_EGAT_Smart_Grid/egat_phabong.avif",
            video: "/img/ourwork/_QC/2024-02_EGAT_Smart_Grid/egat_phabong.mp4",
        },
        {
            id: 9,
            title: "2024-03_tanland",
            header: "Tan Land - 2024",
            img: "/img/ourwork/_QC/2024-03_tanland/poster.avif",
            link: "/ourwork/tanland",
            year: "2024",
            slide1: "/img/ourwork/_QC/2024-03_tanland/tanland.avif",
            video: "/img/ourwork/_QC/2024-03_tanland/tanland.mp4",
        },
        {
            id: 10,
            title: "2024-04_Conan_O'Brien_Must_Go",
            header: "Conan O'Brien Must Go - 2024",
            img: "/img/ourwork/_QC/2024-04_Conan_O'Brien_Must_Go/conan_poster.avif",
            link: "/ourwork/conan_o",
            year: "2024",
            slide1: "/img/ourwork/_QC/2024-04_Conan_O'Brien_Must_Go/conan.avif",
            video: "/img/ourwork/_QC/2024-04_Conan_O'Brien_Must_Go/conan.mp4",
        },
        {
            id: 11,
            title: "2024-05_Royal_Chitralada_Project",
            header: "Royal Chitralada Project - 2024",
            img: "/img/ourwork/_QC/2024-05_Royal_Chitralada_Project/rcp_poster.avif",
            link: "/ourwork/royalchitralada",
            year: "2024",
            slide1: "/img/ourwork/_QC/2024-05_Royal_Chitralada_Project/Slide26.avif",
            video: "/img/ourwork/_QC/2024-05_Royal_Chitralada_Project/rcp.mp4",
        },
        {
            id: 12,
            title: "2025-01_yala",
            header: "Yala Symphony of Life - 2025",
            img: "/img/ourwork/_QC/2025-01_yala/yala_poster.avif",
            link: "/ourwork/yala",
            year: "2025",
            slide1: "/img/ourwork/_QC/2025-01_yala/สไลด์1.avif",
            slide2: "/img/ourwork/_QC/2025-01_yala/สไลด์2.avif",
            video: "/img/ourwork/_QC/2025-01_yala/bbs_yala.mp4",
        },
        {
            id: 13,
            title: "2025-02_ptt_or",
            header: "PTT OR - 2025",
            img: "/img/ourwork/_QC/2025-02_ptt_or/ptt_or_poster.avif",
            link: "/ourwork/ptt-or",
            year: "2025",
            slide1: "/img/ourwork/_QC/2025-02_ptt_or/Slide11.avif",
            slide2: "/img/ourwork/_QC/2025-02_ptt_or/Slide28.avif",
            video: "/img/ourwork/_QC/2025-02_ptt_or/ptt_or.mp4",
        },
        {
            id: 14,
            title: "2025-03_Bank_of_Thailand",
            header: "Bank of Thailand - 2025",
            img: "/img/ourwork/_QC/2025-03_Bank_of_Thailand/bank_of_thailand_poster.avif",
            link: "/ourwork/bankofthailand",
            year: "2025",
            slide1: "/img/ourwork/_QC/2025-03_Bank_of_Thailand/botbank.avif",
            video: "/img/ourwork/_QC/2025-03_Bank_of_Thailand/botbank.mp4",
        },
        {
            id: 15,
            title: "2025-04_Department_of_Land",
            header: "Department of Land - 2025",
            img: "/img/ourwork/_QC/2025-04_Department_of_Land/din.avif",
            link: "/ourwork/departmentofland",
            year: "2025",
            slide1: "/img/ourwork/_QC/2025-04_Department_of_Land/Slide22.avif",
            video: "/img/ourwork/_QC/2025-04_Department_of_Land/din.mp4",
        },
        {
            id: 16,
            title: "2025-05_kungkoo_tvc",
            header: "Kungkoo - 2025",
            img: "/img/ourwork/_QC/2025-05_kungkoo_tvc/kungkoo_poster.avif",
            link: "/ourwork/kungkoo",
            year: "2025",
            slide1: "/img/ourwork/_QC/2025-05_kungkoo_tvc/สไลด์1.avif",
            video: "/img/ourwork/_QC/2025-05_kungkoo_tvc/Kungkoo2025_online_15sec.mov",
        },
    ];
